# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5aa2bd3d-ae1e-4b1e-b0bd-e42d6f57ceba";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

#  fileSystems."/home" =
 #   { device = "/dev/disk/by-uuid/a3886764-3f1a-41d4-8420-8852c13a71e8";
  #    fsType = "btrfs";
   # };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/83D0-A151";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
